# -*- coding: utf-8 -*-
"""предсказание моделью.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qU38if52HG12hTU07UlJCivOGOc9gb37
"""

import pickle
import numpy as np

# Load the trained model
with open('model.pkl', 'rb') as f:
    model = pickle.load(f)

def predict(features):
    features_array = np.array(features).reshape(1, -1)
    return model.predict(features_array)[0]